const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Dictionary,
		C3.Plugins.Browser,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.skymen_limit_fps,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.Rotate,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Behaviors.LOS,
		C3.Plugins.Particles,
		C3.Plugins.NinePatch,
		C3.Behaviors.Sin,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Eponesh_GameScore.Cnds.IsMobile,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Exps.float,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Exps.Opacity,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Dictionary.Exps.Get
	];
};
self.C3_JsPropNameTable = [
	{language: 0},
	{Browser: 0},
	{GamePush: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{LimitFPS: 0},
	{Touch: 0},
	{AJAX: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{block_destroy: 0},
	{block_solid: 0},
	{bubble: 0},
	{bounces: 0},
	{Bullet: 0},
	{bullet: 0},
	{game_bg: 0},
	{grid: 0},
	{gui_text: 0},
	{"8Direction": 0},
	{gun_base: 0},
	{gun_muzzle: 0},
	{Solid: 0},
	{level_border: 0},
	{bullet_limit: 0},
	{target: 0},
	{lvl_controller: 0},
	{player_move: 0},
	{Rotate: 0},
	{transition: 0},
	{Anchor: 0},
	{ui_bg: 0},
	{Tween: 0},
	{block_bounce: 0},
	{LineOfSight: 0},
	{player: 0},
	{Text: 0},
	{cursor: 0},
	{reference: 0},
	{mobile_cursor: 0},
	{bricks_particles: 0},
	{bullet_sparks: 0},
	{gui_splash: 0},
	{key: 0},
	{button_text: 0},
	{button_bg: 0},
	{gui_title: 0},
	{Sine: 0},
	{Sine2: 0},
	{Sine3: 0},
	{menu_title: 0},
	{howtoplay_illustration: 0},
	{jeudemots: 0},
	{tryagain_text: 0},
	{DrawingCanvas: 0},
	{dict_text: 0},
	{gameplay: 0},
	{ad_number: 0},
	{lerp_speed: 0},
	{menu_stage: 0},
	{game_loaded: 0},
	{device: 0}
];

self.InstanceType = {
	language: class extends self.IDictionaryInstance {},
	Browser: class extends self.IInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	LimitFPS: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	block_destroy: class extends self.ISpriteInstance {},
	block_solid: class extends self.ITiledBackgroundInstance {},
	bubble: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	game_bg: class extends self.ITiledBackgroundInstance {},
	grid: class extends self.ITiledBackgroundInstance {},
	gui_text: class extends self.ITextInstance {},
	gun_base: class extends self.ISpriteInstance {},
	gun_muzzle: class extends self.ISpriteInstance {},
	level_border: class extends self.ISpriteInstance {},
	lvl_controller: class extends self.ISpriteInstance {},
	player_move: class extends self.ISpriteInstance {},
	transition: class extends self.ISpriteInstance {},
	ui_bg: class extends self.ITiledBackgroundInstance {},
	block_bounce: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	cursor: class extends self.ISpriteInstance {},
	reference: class extends self.ISpriteInstance {},
	mobile_cursor: class extends self.ISpriteInstance {},
	bricks_particles: class extends self.IParticlesInstance {},
	bullet_sparks: class extends self.IParticlesInstance {},
	gui_splash: class extends self.IWorldInstance {},
	button_text: class extends self.ITextInstance {},
	button_bg: class extends self.IWorldInstance {},
	gui_title: class extends self.ITextInstance {},
	menu_title: class extends self.ISpriteInstance {},
	howtoplay_illustration: class extends self.ISpriteInstance {},
	jeudemots: class extends self.ISpriteInstance {},
	tryagain_text: class extends self.ITextInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	dict_text: class extends self.ITextInstance {}
}